In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("heart.csv")

In [3]:
data.dtypes

Unnamed: 0      int64
age             int64
sex             int64
cp              int64
trestbps        int64
chol            int64
fbs             int64
restecg         int64
thalach         int64
exang           int64
oldpeak       float64
slope           int64
ca              int64
target          int64
dtype: object

In [4]:
data.head()

Unnamed: 0  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0           1   63    1   3       145   233    1        0      150      0   
1           2   37    1   2       130   250    0        1      187      0   
2           3   41    0   1       130   204    0        0      172      0   
3           4   56    1   1       120   236    0        1      178      0   
4           5   57    0   0       120   354    0        1      163      1   

   oldpeak  slope  ca  target  
0      2.3      0   0       1  
1      3.5      0   0       1  
2      1.4      2   0       1  
3      0.8      2   0       1  
4      0.6      2   0       1

In [5]:
x=data[["age"]]
y=data[["target"]]


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler1=StandardScaler()
scaler2=StandardScaler()

In [9]:
train_x=scaler1.fit_transform(train_x)
test_x=scaler2.fit_transform(test_x )

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [10]:
train_x,test_x,train_y,test_y

(array([[-1.32773282],
        [ 1.24903178],
        [ 0.35276583],
        [ 0.91293205],
        [ 0.24073259],
        [ 0.46479907],
        [ 0.35276583],
        [-0.87959984],
        [-0.43146687],
        [ 0.46479907],
        [-1.21569957],
        [ 0.12869935],
        [ 0.0166661 ],
        [ 1.13699853],
        [-0.43146687],
        [ 0.35276583],
        [-0.31943363],
        [-0.09536714],
        [ 0.46479907],
        [ 1.36106502],
        [ 1.02496529],
        [-0.54350011],
        [-1.88789903],
        [ 0.46479907],
        [-0.09536714],
        [ 1.36106502],
        [ 1.36106502],
        [-0.43146687],
        [ 1.36106502],
        [ 2.48139745],
        [ 0.8008988 ],
        [ 1.58513151],
        [ 0.68886556],
        [-1.77586579],
        [ 1.02496529],
        [ 1.24903178],
        [ 0.24073259],
        [-0.87959984],
        [ 0.46479907],
        [ 0.8008988 ],
        [ 0.91293205],
        [ 1.69716475],
        [-1.32773282],
        [-0

In [78]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [79]:
log_reg.fit(train_x , train_y )

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [80]:
pred_y=log_reg.predict(test_x)
pred_y

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1], dtype=int64)

In [14]:
test_y

target
225       0
152       1
228       0
201       0
52        1
245       0
175       0
168       0
223       0
217       0
111       1
135       1
218       0
12        1
15        1
66        1
97        1
90        1
198       0
103       1
22        1
212       0
226       0
264       0
133       1
216       0
275       0
270       0
154       1
55        1
..      ...
255       0
134       1
8         1
157       1
241       0
240       0
81        1
214       0
167       0
5         1
59        1
92        1
274       0
34        1
145       1
116       1
188       0
246       0
7         1
45        1
129       1
122       1
63        1
124       1
227       0
146       1
302       0
26        1
108       1
89        1

[61 rows x 1 columns]

In [81]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

results = confusion_matrix(test_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(test_y, pred_y))
print ('Report : ')
print (classification_report(test_y, pred_y))

Confusion Matrix :
[[18  9]
 [10 24]]
Accuracy Score : 0.6885245901639344
Report : 
              precision    recall  f1-score   support

           0       0.64      0.67      0.65        27
           1       0.73      0.71      0.72        34

   micro avg       0.69      0.69      0.69        61
   macro avg       0.69      0.69      0.69        61
weighted avg       0.69      0.69      0.69        61



##Heart disease on the basis of resting blood pressure

In [17]:
x=data[['trestbps']]
y=data[['target']]

In [20]:
from sklearn.model_selection import train_test_split

In [24]:
train_x , test_x , train_y , test_y = train_test_split(x , y , test_size = 0.2 , random_state = 0)

In [27]:
from sklearn.preprocessing import StandardScaler
scaler1=StandardScaler()
scaler2=StandardScaler()

In [28]:
train_x=scaler1.fit_transform(train_x)
test_x=scaler2.fit_transform(test_x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [29]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression

In [82]:
log_reg.fit(train_x,train_y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [85]:
pred_y = log_reg.predict(test_x)
pred_y 

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1], dtype=int64)

In [35]:
test_y

target
225       0
152       1
228       0
201       0
52        1
245       0
175       0
168       0
223       0
217       0
111       1
135       1
218       0
12        1
15        1
66        1
97        1
90        1
198       0
103       1
22        1
212       0
226       0
264       0
133       1
216       0
275       0
270       0
154       1
55        1
..      ...
255       0
134       1
8         1
157       1
241       0
240       0
81        1
214       0
167       0
5         1
59        1
92        1
274       0
34        1
145       1
116       1
188       0
246       0
7         1
45        1
129       1
122       1
63        1
124       1
227       0
146       1
302       0
26        1
108       1
89        1

[61 rows x 1 columns]

In [86]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

results = confusion_matrix(test_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(test_y, pred_y))
print ('Report : ')
print (classification_report(test_y, pred_y))

Confusion Matrix :
[[18  9]
 [10 24]]
Accuracy Score : 0.6885245901639344
Report : 
              precision    recall  f1-score   support

           0       0.64      0.67      0.65        27
           1       0.73      0.71      0.72        34

   micro avg       0.69      0.69      0.69        61
   macro avg       0.69      0.69      0.69        61
weighted avg       0.69      0.69      0.69        61



###Heart disease on the basis of maximum heart rate achieved¶


In [44]:
x=data[["thalach"]]
y=data[["target"]]

In [46]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=0)

In [48]:
from sklearn.preprocessing import StandardScaler
scaler1=StandardScaler()
scaler2=StandardScaler()


In [49]:
train_x = scaler1.fit_transform(train_x)
test_x = scaler2.fit_transform(test_x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [50]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(train_x , train_y )

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [51]:
pred_y = log_reg.predict(test_x)
pred_y 

array([0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0], dtype=int64)

In [52]:
test_y

target
225       0
152       1
228       0
201       0
52        1
245       0
175       0
168       0
223       0
217       0
111       1
135       1
218       0
12        1
15        1
66        1
97        1
90        1
198       0
103       1
22        1
212       0
226       0
264       0
133       1
216       0
275       0
270       0
154       1
55        1
..      ...
255       0
134       1
8         1
157       1
241       0
240       0
81        1
214       0
167       0
5         1
59        1
92        1
274       0
34        1
145       1
116       1
188       0
246       0
7         1
45        1
129       1
122       1
63        1
124       1
227       0
146       1
302       0
26        1
108       1
89        1

[61 rows x 1 columns]

In [53]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

results = confusion_matrix(test_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(test_y, pred_y))
print ('Report : ')
print (classification_report(test_y, pred_y))

Confusion Matrix :
[[17 10]
 [ 6 28]]
Accuracy Score : 0.7377049180327869
Report : 
              precision    recall  f1-score   support

           0       0.74      0.63      0.68        27
           1       0.74      0.82      0.78        34

   micro avg       0.74      0.74      0.74        61
   macro avg       0.74      0.73      0.73        61
weighted avg       0.74      0.74      0.73        61



question - 1 (d) :
we find maximum accuracy and F1 score on the basis of Maximun Heart rate achieved that's why this factor more influences

In [55]:
#qstn 2
x=data[["cp"]]
y=data[["target"]]

In [56]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y , test_y = train_test_split(x , y , test_size = 0.2 , random_state = 0)

In [57]:
from sklearn.naive_bayes import GaussianNB
GB = GaussianNB()
GB.fit(train_x , train_y )

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [58]:
pred_y = GB.predict(test_x)
pred_y 

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0], dtype=int64)

In [60]:
test_y

target
225       0
152       1
228       0
201       0
52        1
245       0
175       0
168       0
223       0
217       0
111       1
135       1
218       0
12        1
15        1
66        1
97        1
90        1
198       0
103       1
22        1
212       0
226       0
264       0
133       1
216       0
275       0
270       0
154       1
55        1
..      ...
255       0
134       1
8         1
157       1
241       0
240       0
81        1
214       0
167       0
5         1
59        1
92        1
274       0
34        1
145       1
116       1
188       0
246       0
7         1
45        1
129       1
122       1
63        1
124       1
227       0
146       1
302       0
26        1
108       1
89        1

[61 rows x 1 columns]

In [61]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

results = confusion_matrix(test_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(test_y, pred_y))
print ('Report : ')
print (classification_report(test_y, pred_y))

Confusion Matrix :
[[20  7]
 [ 6 28]]
Accuracy Score : 0.7868852459016393
Report : 
              precision    recall  f1-score   support

           0       0.77      0.74      0.75        27
           1       0.80      0.82      0.81        34

   micro avg       0.79      0.79      0.79        61
   macro avg       0.78      0.78      0.78        61
weighted avg       0.79      0.79      0.79        61



In [63]:
#b
x = data[["chol"]]
y = data[["target"]]

In [64]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y , test_y = train_test_split(x , y , test_size = 0.2 , random_state = 0)

In [65]:
from sklearn.preprocessing import StandardScaler
scaler1 = StandardScaler()
scaler2 = StandardScaler()

In [66]:
train_x = scaler1.fit_transform(train_x)
test_x = scaler2.fit_transform(test_x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [ ]:
from sklearn.naive_bayes import GaussianNB
GB = GaussianNB()
GB.fit(train_x , train_y )

In [68]:
pred_y = GB.predict(test_x)
pred_y 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [69]:
test_y

target
225       0
152       1
228       0
201       0
52        1
245       0
175       0
168       0
223       0
217       0
111       1
135       1
218       0
12        1
15        1
66        1
97        1
90        1
198       0
103       1
22        1
212       0
226       0
264       0
133       1
216       0
275       0
270       0
154       1
55        1
..      ...
255       0
134       1
8         1
157       1
241       0
240       0
81        1
214       0
167       0
5         1
59        1
92        1
274       0
34        1
145       1
116       1
188       0
246       0
7         1
45        1
129       1
122       1
63        1
124       1
227       0
146       1
302       0
26        1
108       1
89        1

[61 rows x 1 columns]

In [70]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

results = confusion_matrix(test_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(test_y, pred_y))
print ('Report : ')
print (classification_report(test_y, pred_y))

Confusion Matrix :
[[ 0 27]
 [ 0 34]]
Accuracy Score : 0.5573770491803278
Report : 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        27
           1       0.56      1.00      0.72        34

   micro avg       0.56      0.56      0.56        61
   macro avg       0.28      0.50      0.36        61
weighted avg       0.31      0.56      0.40        61



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [72]:
#c
x = data[["ca"]]
y = data[["target"]]


In [73]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y , test_y = train_test_split(x , y , test_size = 0.2 , random_state = 0)

In [74]:
from sklearn.naive_bayes import GaussianNB
GB = GaussianNB()
GB.fit(train_x , train_y )

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [75]:
pred_y = GB.predict(test_x)
pred_y 

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [76]:
test_y

target
225       0
152       1
228       0
201       0
52        1
245       0
175       0
168       0
223       0
217       0
111       1
135       1
218       0
12        1
15        1
66        1
97        1
90        1
198       0
103       1
22        1
212       0
226       0
264       0
133       1
216       0
275       0
270       0
154       1
55        1
..      ...
255       0
134       1
8         1
157       1
241       0
240       0
81        1
214       0
167       0
5         1
59        1
92        1
274       0
34        1
145       1
116       1
188       0
246       0
7         1
45        1
129       1
122       1
63        1
124       1
227       0
146       1
302       0
26        1
108       1
89        1

[61 rows x 1 columns]

In [77]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

results = confusion_matrix(test_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(test_y, pred_y))
print ('Report : ')
print (classification_report(test_y, pred_y))

Confusion Matrix :
[[ 7 20]
 [ 4 30]]
Accuracy Score : 0.6065573770491803
Report : 
              precision    recall  f1-score   support

           0       0.64      0.26      0.37        27
           1       0.60      0.88      0.71        34

   micro avg       0.61      0.61      0.61        61
   macro avg       0.62      0.57      0.54        61
weighted avg       0.62      0.61      0.56        61

